### PR TITLE
Update dynamodb-geo to work with version 1.10.61 of aws-java-sdk

### PR DESCRIPTION
**Pull request by ghost**
**Issue**: dynamodb-geo-1.0.0.jar can not be deployed in a runtime environment with the latest aws-java-sdk ( tested with 1.10.61)

**Use case**: I want to apply dynamodb-geo in a lambda function. In this function I need the recent aws-java-sdk. If I deploy dynamodb-geo-1.0.0.jar I get errors like Exception in thread "main" java.lang.NoClassDefFoundError: org/codehaus/jackson/map/ObjectMapper

**Cause**: The current dynamodb-geo-1.0.0 requires  jackson-1.8.9 (via aws-java-sdk-1.5.5). Version 1.8.9 of Jackson uses java packaging _org.codehaus.jackson_. 
aws-java-sdk-1.10.61 requires jackson-2.5. Version 2.5.\* of Jackson uses packaging _com.fasterxml.jackson_.

**Solution**: Release a new version of dynamodb-geo (I used 1.1.0 in the pom.xml) and apply the new jackson package names in the affected files. 

I wrote a simple test client here: https://github.com/peterfennema/dynamodb-geo/blob/topic-update-to-aws-java-sdk-1.10.61/srctest/nl/peterfennema/geo/SimpleGeoClientTest.java

### CODE REVIEW

**Comment by brianjd** [comment]
Can this be merged?  It's been nearly a year, can it at least receive a response?

**Comment by peterfennema** [comment]
@brianjd I concluded that AWS has abandoned this project. They should mark it as such, so that people do not invest their time to make it work. Or, even better, start supporting it again....

**Comment by SirWellington** [comment]
I ditched Dynamo for GeoQueries, and instead went over to PostgreSQL with the PostGIS extension. It is much faster and a lot cheaper too.

**Comment by kashifaliquazi** [comment]
Can Someone Please merge this pull request since this is a blocker.  
@brianjd  @SirWellington  @brianjd @jpeddicord  

Or if anybody know whats the another way to get this library working.

any help would be appreciated.

**Comment by jpeddicord** [comment]
@kashifaliquazi Unfortunately, this awslabs project is no longer supported. This project was intended to be archived some time ago, however due to an administrative error it was not completed. I'll finish that now.

You're welcome to use one of the many [community forks of this project](https://github.com/amazon-archives/dynamodb-geo/network) or fork it yourself. Sorry for the inconvenience.
